name: project-env
channels:
  - conda-forge
  - defaults
dependencies:
  - scikit-learn=1.2.1
  - python=3.11
  - pandas=2.1.4
  - matplotlib=3.8
  - jupyterlab
prefix: C:\Users\charl\miniconda3\envs\dstoolbox
